// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pratikasr/trustregistry/v1/query.proto

package trustregistry

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryGetTrustRegistryRequest is the request type for the Query/GetTrustRegistry RPC method.
type QueryGetTrustRegistryRequest struct {
	Did               string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	ActiveGfOnly      bool   `protobuf:"varint,2,opt,name=active_gf_only,json=activeGfOnly,proto3" json:"active_gf_only,omitempty"`
	PreferredLanguage string `protobuf:"bytes,3,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
}

func (m *QueryGetTrustRegistryRequest) Reset()         { *m = QueryGetTrustRegistryRequest{} }
func (m *QueryGetTrustRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTrustRegistryRequest) ProtoMessage()    {}
func (*QueryGetTrustRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da42d58df591d77, []int{0}
}
func (m *QueryGetTrustRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTrustRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTrustRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTrustRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTrustRegistryRequest.Merge(m, src)
}
func (m *QueryGetTrustRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTrustRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTrustRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTrustRegistryRequest proto.InternalMessageInfo

func (m *QueryGetTrustRegistryRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *QueryGetTrustRegistryRequest) GetActiveGfOnly() bool {
	if m != nil {
		return m.ActiveGfOnly
	}
	return false
}

func (m *QueryGetTrustRegistryRequest) GetPreferredLanguage() string {
	if m != nil {
		return m.PreferredLanguage
	}
	return ""
}

// QueryGetTrustRegistryResponse is the response type for the Query/GetTrustRegistry RPC method.
type QueryGetTrustRegistryResponse struct {
	TrustRegistry *TrustRegistry                `protobuf:"bytes,1,opt,name=trust_registry,json=trustRegistry,proto3" json:"trust_registry,omitempty"`
	Versions      []GovernanceFrameworkVersion  `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions"`
	Documents     []GovernanceFrameworkDocument `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents"`
}

func (m *QueryGetTrustRegistryResponse) Reset()         { *m = QueryGetTrustRegistryResponse{} }
func (m *QueryGetTrustRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTrustRegistryResponse) ProtoMessage()    {}
func (*QueryGetTrustRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da42d58df591d77, []int{1}
}
func (m *QueryGetTrustRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTrustRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTrustRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTrustRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTrustRegistryResponse.Merge(m, src)
}
func (m *QueryGetTrustRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTrustRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTrustRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTrustRegistryResponse proto.InternalMessageInfo

func (m *QueryGetTrustRegistryResponse) GetTrustRegistry() *TrustRegistry {
	if m != nil {
		return m.TrustRegistry
	}
	return nil
}

func (m *QueryGetTrustRegistryResponse) GetVersions() []GovernanceFrameworkVersion {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *QueryGetTrustRegistryResponse) GetDocuments() []GovernanceFrameworkDocument {
	if m != nil {
		return m.Documents
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetTrustRegistryRequest)(nil), "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest")
	proto.RegisterType((*QueryGetTrustRegistryResponse)(nil), "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse")
}

func init() {
	proto.RegisterFile("pratikasr/trustregistry/v1/query.proto", fileDescriptor_7da42d58df591d77)
}

var fileDescriptor_7da42d58df591d77 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x8b, 0x13, 0x31,
	0x14, 0xc7, 0x9b, 0x56, 0x65, 0x37, 0xab, 0xcb, 0x1a, 0x3c, 0x0c, 0x65, 0x1d, 0x4b, 0x91, 0x65,
	0x3c, 0x38, 0x61, 0x2b, 0xf8, 0x03, 0x3c, 0x2d, 0x62, 0x2f, 0x82, 0x3a, 0x88, 0x88, 0x1e, 0x86,
	0xec, 0xcc, 0x6b, 0x0c, 0x3b, 0x4d, 0x66, 0x93, 0xcc, 0xc8, 0x20, 0x5e, 0x04, 0xef, 0x82, 0xff,
	0x84, 0xff, 0x81, 0x67, 0x6f, 0x7b, 0x2c, 0x78, 0xf1, 0x24, 0xd2, 0xfa, 0x87, 0xc8, 0xfc, 0xb0,
	0x5a, 0xb1, 0x03, 0xee, 0xed, 0x25, 0x79, 0xdf, 0x4f, 0xde, 0xfb, 0xbe, 0x87, 0xf7, 0x52, 0xcd,
	0xac, 0x38, 0x62, 0x46, 0x53, 0xab, 0x33, 0x63, 0x35, 0x70, 0x61, 0xac, 0x2e, 0x68, 0xbe, 0x4f,
	0x8f, 0x33, 0xd0, 0x85, 0x9f, 0x6a, 0x65, 0x15, 0xe9, 0x2f, 0xf3, 0xfc, 0x95, 0x3c, 0x3f, 0xdf,
	0xef, 0xef, 0x72, 0xa5, 0x78, 0x02, 0x94, 0xa5, 0x82, 0x32, 0x29, 0x95, 0x65, 0x56, 0x28, 0x69,
	0x6a, 0x65, 0xff, 0x12, 0x57, 0x5c, 0x55, 0x21, 0x2d, 0xa3, 0xe6, 0xb6, 0xed, 0x5f, 0x5b, 0xa4,
	0xd0, 0xa8, 0x87, 0xef, 0x10, 0xde, 0x7d, 0x5c, 0xd6, 0x31, 0x06, 0xfb, 0xa4, 0x4c, 0x0c, 0x9a,
	0xc4, 0x00, 0x8e, 0x33, 0x30, 0x96, 0xec, 0xe0, 0x5e, 0x2c, 0x62, 0x07, 0x0d, 0x90, 0xb7, 0x19,
	0x94, 0x21, 0xb9, 0x8a, 0xb7, 0x59, 0x64, 0x45, 0x0e, 0x21, 0x9f, 0x84, 0x4a, 0x26, 0x85, 0xd3,
	0x1d, 0x20, 0x6f, 0x23, 0x38, 0x5f, 0xdf, 0x8e, 0x27, 0x0f, 0x65, 0x52, 0x90, 0xeb, 0x98, 0xa4,
	0x1a, 0x26, 0xa0, 0x35, 0xc4, 0x61, 0xc2, 0x24, 0xcf, 0x18, 0x07, 0xa7, 0x57, 0x61, 0x2e, 0x2e,
	0x5f, 0x1e, 0x34, 0x0f, 0xc3, 0x8f, 0x5d, 0x7c, 0x79, 0x4d, 0x1d, 0x26, 0x55, 0xd2, 0x00, 0x79,
	0x84, 0xb7, 0xab, 0x4e, 0xc2, 0x5f, 0xad, 0x54, 0x35, 0x6d, 0x8d, 0xae, 0xf9, 0xeb, 0xad, 0xf3,
	0x57, 0x51, 0x17, 0xec, 0x9f, 0x47, 0xf2, 0x0c, 0x6f, 0xe4, 0xa0, 0x4d, 0xe9, 0xa5, 0xd3, 0x1d,
	0xf4, 0xbc, 0xad, 0xd1, 0xcd, 0x36, 0xd6, 0x58, 0xe5, 0xa0, 0x25, 0x93, 0x11, 0xdc, 0xd7, 0x6c,
	0x0a, 0xaf, 0x94, 0x3e, 0x7a, 0x5a, 0xcb, 0x0f, 0xce, 0x9c, 0x7c, 0xbb, 0xd2, 0x09, 0x96, 0x34,
	0xf2, 0x02, 0x6f, 0xc6, 0x2a, 0xca, 0xa6, 0x20, 0xad, 0x71, 0x7a, 0x15, 0xfa, 0xd6, 0x7f, 0xa2,
	0xef, 0x35, 0xfa, 0x86, 0xfd, 0x9b, 0x37, 0xfa, 0x8c, 0xf0, 0xd9, 0xca, 0x2a, 0xf2, 0x09, 0xe1,
	0x9d, 0xbf, 0xfd, 0x22, 0xb7, 0xdb, 0x3e, 0x6a, 0x1b, 0x75, 0xff, 0xce, 0x29, 0x94, 0xf5, 0x70,
	0x86, 0xfe, 0xdb, 0x2f, 0x3f, 0x3e, 0x74, 0x3d, 0xb2, 0xf7, 0x8f, 0x6d, 0x5b, 0x19, 0x1a, 0x7d,
	0x1d, 0x8b, 0xf8, 0xcd, 0xc1, 0xdd, 0x93, 0xb9, 0x8b, 0x66, 0x73, 0x17, 0x7d, 0x9f, 0xbb, 0xe8,
	0xfd, 0xc2, 0xed, 0xcc, 0x16, 0x6e, 0xe7, 0xeb, 0xc2, 0xed, 0x3c, 0x1f, 0x72, 0x61, 0x5f, 0x66,
	0x87, 0x7e, 0xa4, 0xa6, 0x74, 0xcd, 0x0e, 0x1f, 0x9e, 0xab, 0x76, 0xf7, 0xc6, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x14, 0x9d, 0x37, 0x72, 0x5d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetTrustRegistry returns the trust registry information.
	GetTrustRegistry(ctx context.Context, in *QueryGetTrustRegistryRequest, opts ...grpc.CallOption) (*QueryGetTrustRegistryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetTrustRegistry(ctx context.Context, in *QueryGetTrustRegistryRequest, opts ...grpc.CallOption) (*QueryGetTrustRegistryResponse, error) {
	out := new(QueryGetTrustRegistryResponse)
	err := c.cc.Invoke(ctx, "/pratikasr.trustregistry.v1.Query/GetTrustRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetTrustRegistry returns the trust registry information.
	GetTrustRegistry(context.Context, *QueryGetTrustRegistryRequest) (*QueryGetTrustRegistryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetTrustRegistry(ctx context.Context, req *QueryGetTrustRegistryRequest) (*QueryGetTrustRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrustRegistry not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetTrustRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTrustRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTrustRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pratikasr.trustregistry.v1.Query/GetTrustRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTrustRegistry(ctx, req.(*QueryGetTrustRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pratikasr.trustregistry.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrustRegistry",
			Handler:    _Query_GetTrustRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pratikasr/trustregistry/v1/query.proto",
}

func (m *QueryGetTrustRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTrustRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTrustRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PreferredLanguage) > 0 {
		i -= len(m.PreferredLanguage)
		copy(dAtA[i:], m.PreferredLanguage)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PreferredLanguage)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ActiveGfOnly {
		i--
		if m.ActiveGfOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTrustRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTrustRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTrustRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Documents) > 0 {
		for iNdEx := len(m.Documents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Documents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Versions) > 0 {
		for iNdEx := len(m.Versions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Versions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TrustRegistry != nil {
		{
			size, err := m.TrustRegistry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetTrustRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ActiveGfOnly {
		n += 2
	}
	l = len(m.PreferredLanguage)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTrustRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustRegistry != nil {
		l = m.TrustRegistry.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Versions) > 0 {
		for _, e := range m.Versions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.Documents) > 0 {
		for _, e := range m.Documents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetTrustRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTrustRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTrustRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveGfOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ActiveGfOnly = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferredLanguage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreferredLanguage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTrustRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTrustRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTrustRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustRegistry == nil {
				m.TrustRegistry = &TrustRegistry{}
			}
			if err := m.TrustRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Versions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Versions = append(m.Versions, GovernanceFrameworkVersion{})
			if err := m.Versions[len(m.Versions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Documents = append(m.Documents, GovernanceFrameworkDocument{})
			if err := m.Documents[len(m.Documents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
