// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pratikasr/trustregistry/v1/tx.proto

package trustregistry

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateTrustRegistry defines the Msg/CreateTrustRegistry request type.
type MsgCreateTrustRegistry struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Did      string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	Aka      string `protobuf:"bytes,3,opt,name=aka,proto3" json:"aka,omitempty"`
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	DocUrl   string `protobuf:"bytes,5,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	DocHash  string `protobuf:"bytes,6,opt,name=doc_hash,json=docHash,proto3" json:"doc_hash,omitempty"`
}

func (m *MsgCreateTrustRegistry) Reset()         { *m = MsgCreateTrustRegistry{} }
func (m *MsgCreateTrustRegistry) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTrustRegistry) ProtoMessage()    {}
func (*MsgCreateTrustRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_85ed19941080cdb5, []int{0}
}
func (m *MsgCreateTrustRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateTrustRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateTrustRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateTrustRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTrustRegistry.Merge(m, src)
}
func (m *MsgCreateTrustRegistry) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateTrustRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTrustRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTrustRegistry proto.InternalMessageInfo

func (m *MsgCreateTrustRegistry) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateTrustRegistry) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *MsgCreateTrustRegistry) GetAka() string {
	if m != nil {
		return m.Aka
	}
	return ""
}

func (m *MsgCreateTrustRegistry) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *MsgCreateTrustRegistry) GetDocUrl() string {
	if m != nil {
		return m.DocUrl
	}
	return ""
}

func (m *MsgCreateTrustRegistry) GetDocHash() string {
	if m != nil {
		return m.DocHash
	}
	return ""
}

// MsgCreateTrustRegistryResponse defines the Msg/CreateTrustRegistry response type.
type MsgCreateTrustRegistryResponse struct {
}

func (m *MsgCreateTrustRegistryResponse) Reset()         { *m = MsgCreateTrustRegistryResponse{} }
func (m *MsgCreateTrustRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTrustRegistryResponse) ProtoMessage()    {}
func (*MsgCreateTrustRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85ed19941080cdb5, []int{1}
}
func (m *MsgCreateTrustRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateTrustRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateTrustRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateTrustRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTrustRegistryResponse.Merge(m, src)
}
func (m *MsgCreateTrustRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateTrustRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTrustRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTrustRegistryResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateTrustRegistry)(nil), "pratikasr.trustregistry.v1.MsgCreateTrustRegistry")
	proto.RegisterType((*MsgCreateTrustRegistryResponse)(nil), "pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse")
}

func init() {
	proto.RegisterFile("pratikasr/trustregistry/v1/tx.proto", fileDescriptor_85ed19941080cdb5)
}

var fileDescriptor_85ed19941080cdb5 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3f, 0x4f, 0x32, 0x31,
	0x18, 0xa7, 0x2f, 0x2f, 0x7f, 0xde, 0xe6, 0x1d, 0xcc, 0x69, 0xa4, 0xdc, 0xd0, 0x10, 0x5c, 0x0c,
	0x89, 0x77, 0x01, 0x37, 0xe2, 0x22, 0x2e, 0x2e, 0x2c, 0xa7, 0x2e, 0x2e, 0xa4, 0xdc, 0x35, 0xbd,
	0x0b, 0x1c, 0x25, 0x7d, 0x7a, 0x44, 0x37, 0x63, 0xe2, 0xee, 0xe0, 0x07, 0x61, 0xf0, 0x43, 0x38,
	0x19, 0xe2, 0xe4, 0x68, 0x60, 0xe0, 0x6b, 0x98, 0xde, 0x01, 0x89, 0x09, 0x0c, 0x6e, 0xfd, 0xfd,
	0xcd, 0xf3, 0xb4, 0xc5, 0x47, 0x63, 0xc5, 0x74, 0x34, 0x60, 0xa0, 0x5c, 0xad, 0x12, 0xd0, 0x8a,
	0x8b, 0x08, 0xb4, 0xba, 0x77, 0x27, 0x4d, 0x57, 0xdf, 0x39, 0x63, 0x25, 0xb5, 0xb4, 0xec, 0x8d,
	0xc9, 0xf9, 0x61, 0x72, 0x26, 0x4d, 0xbb, 0xe2, 0x4b, 0x88, 0x25, 0xb8, 0x31, 0x08, 0x93, 0x89,
	0x41, 0x64, 0x21, 0xbb, 0x9a, 0x09, 0xbd, 0x14, 0xb9, 0x19, 0xc8, 0xa4, 0xfa, 0x3b, 0xc2, 0x87,
	0x5d, 0x10, 0x17, 0x8a, 0x33, 0xcd, 0xaf, 0x4d, 0xa3, 0xb7, 0x6a, 0xb4, 0x5a, 0xb8, 0xe4, 0x1b,
	0x5a, 0x2a, 0x82, 0x6a, 0xe8, 0xf8, 0x5f, 0x87, 0x7c, 0xbc, 0x9e, 0x1c, 0xac, 0xd2, 0xe7, 0x41,
	0xa0, 0x38, 0xc0, 0x95, 0x56, 0xd1, 0x48, 0x78, 0x6b, 0xa3, 0xb5, 0x87, 0xf3, 0x41, 0x14, 0x90,
	0x3f, 0xc6, 0xef, 0x99, 0xa3, 0x61, 0xd8, 0x80, 0x91, 0x7c, 0xc6, 0xb0, 0x01, 0xb3, 0x6c, 0x5c,
	0x1e, 0xb2, 0x91, 0x48, 0x98, 0xe0, 0xe4, 0x6f, 0x4a, 0x6f, 0xb0, 0x55, 0xc1, 0xa5, 0x40, 0xfa,
	0xbd, 0x44, 0x0d, 0x49, 0x21, 0x95, 0x8a, 0x81, 0xf4, 0x6f, 0xd4, 0xd0, 0xaa, 0xe2, 0xb2, 0x11,
	0x42, 0x06, 0x21, 0x29, 0xa6, 0x8a, 0x31, 0x5e, 0x32, 0x08, 0xdb, 0xff, 0x1f, 0x97, 0xd3, 0xc6,
	0x7a, 0x82, 0x7a, 0x0d, 0xd3, 0xed, 0xfb, 0x78, 0x1c, 0xc6, 0x72, 0x04, 0xbc, 0xf5, 0x82, 0x70,
	0xbe, 0x0b, 0xc2, 0x7a, 0x42, 0x78, 0x7f, 0xeb, 0xde, 0xce, 0xee, 0x3b, 0x76, 0xb6, 0x77, 0xdb,
	0xed, 0xdf, 0x67, 0xd6, 0xf3, 0xd8, 0x85, 0x87, 0xe5, 0xb4, 0x81, 0x3a, 0x67, 0x6f, 0x73, 0x8a,
	0x66, 0x73, 0x8a, 0xbe, 0xe6, 0x14, 0x3d, 0x2f, 0x68, 0x6e, 0xb6, 0xa0, 0xb9, 0xcf, 0x05, 0xcd,
	0xdd, 0xd6, 0x45, 0xa4, 0xc3, 0xa4, 0xef, 0xf8, 0x32, 0x76, 0x77, 0xfc, 0x91, 0x7e, 0x31, 0x7d,
	0xce, 0xd3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x17, 0x54, 0x6a, 0x45, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateTrustRegistry creates a new trust registry.
	CreateTrustRegistry(ctx context.Context, in *MsgCreateTrustRegistry, opts ...grpc.CallOption) (*MsgCreateTrustRegistryResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateTrustRegistry(ctx context.Context, in *MsgCreateTrustRegistry, opts ...grpc.CallOption) (*MsgCreateTrustRegistryResponse, error) {
	out := new(MsgCreateTrustRegistryResponse)
	err := c.cc.Invoke(ctx, "/pratikasr.trustregistry.v1.Msg/CreateTrustRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateTrustRegistry creates a new trust registry.
	CreateTrustRegistry(context.Context, *MsgCreateTrustRegistry) (*MsgCreateTrustRegistryResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateTrustRegistry(ctx context.Context, req *MsgCreateTrustRegistry) (*MsgCreateTrustRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrustRegistry not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateTrustRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTrustRegistry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTrustRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pratikasr.trustregistry.v1.Msg/CreateTrustRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTrustRegistry(ctx, req.(*MsgCreateTrustRegistry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pratikasr.trustregistry.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrustRegistry",
			Handler:    _Msg_CreateTrustRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pratikasr/trustregistry/v1/tx.proto",
}

func (m *MsgCreateTrustRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateTrustRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateTrustRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DocHash) > 0 {
		i -= len(m.DocHash)
		copy(dAtA[i:], m.DocHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DocUrl) > 0 {
		i -= len(m.DocUrl)
		copy(dAtA[i:], m.DocUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Language) > 0 {
		i -= len(m.Language)
		copy(dAtA[i:], m.Language)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Language)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Aka) > 0 {
		i -= len(m.Aka)
		copy(dAtA[i:], m.Aka)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Aka)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateTrustRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateTrustRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateTrustRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateTrustRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Aka)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Language)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DocUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DocHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateTrustRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateTrustRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateTrustRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateTrustRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aka", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Aka = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Language = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateTrustRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateTrustRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateTrustRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
