// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package trustregistryv1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_QueryGetTrustRegistryRequest                    protoreflect.MessageDescriptor
	fd_QueryGetTrustRegistryRequest_did                protoreflect.FieldDescriptor
	fd_QueryGetTrustRegistryRequest_active_gf_only     protoreflect.FieldDescriptor
	fd_QueryGetTrustRegistryRequest_preferred_language protoreflect.FieldDescriptor
)

func init() {
	file_pratikasr_trustregistry_v1_query_proto_init()
	md_QueryGetTrustRegistryRequest = File_pratikasr_trustregistry_v1_query_proto.Messages().ByName("QueryGetTrustRegistryRequest")
	fd_QueryGetTrustRegistryRequest_did = md_QueryGetTrustRegistryRequest.Fields().ByName("did")
	fd_QueryGetTrustRegistryRequest_active_gf_only = md_QueryGetTrustRegistryRequest.Fields().ByName("active_gf_only")
	fd_QueryGetTrustRegistryRequest_preferred_language = md_QueryGetTrustRegistryRequest.Fields().ByName("preferred_language")
}

var _ protoreflect.Message = (*fastReflection_QueryGetTrustRegistryRequest)(nil)

type fastReflection_QueryGetTrustRegistryRequest QueryGetTrustRegistryRequest

func (x *QueryGetTrustRegistryRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryGetTrustRegistryRequest)(x)
}

func (x *QueryGetTrustRegistryRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_pratikasr_trustregistry_v1_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryGetTrustRegistryRequest_messageType fastReflection_QueryGetTrustRegistryRequest_messageType
var _ protoreflect.MessageType = fastReflection_QueryGetTrustRegistryRequest_messageType{}

type fastReflection_QueryGetTrustRegistryRequest_messageType struct{}

func (x fastReflection_QueryGetTrustRegistryRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryGetTrustRegistryRequest)(nil)
}
func (x fastReflection_QueryGetTrustRegistryRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryGetTrustRegistryRequest)
}
func (x fastReflection_QueryGetTrustRegistryRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryGetTrustRegistryRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryGetTrustRegistryRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryGetTrustRegistryRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryGetTrustRegistryRequest) Type() protoreflect.MessageType {
	return _fastReflection_QueryGetTrustRegistryRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryGetTrustRegistryRequest) New() protoreflect.Message {
	return new(fastReflection_QueryGetTrustRegistryRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryGetTrustRegistryRequest) Interface() protoreflect.ProtoMessage {
	return (*QueryGetTrustRegistryRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryGetTrustRegistryRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Did != "" {
		value := protoreflect.ValueOfString(x.Did)
		if !f(fd_QueryGetTrustRegistryRequest_did, value) {
			return
		}
	}
	if x.ActiveGfOnly != false {
		value := protoreflect.ValueOfBool(x.ActiveGfOnly)
		if !f(fd_QueryGetTrustRegistryRequest_active_gf_only, value) {
			return
		}
	}
	if x.PreferredLanguage != "" {
		value := protoreflect.ValueOfString(x.PreferredLanguage)
		if !f(fd_QueryGetTrustRegistryRequest_preferred_language, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryGetTrustRegistryRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.did":
		return x.Did != ""
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.active_gf_only":
		return x.ActiveGfOnly != false
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.preferred_language":
		return x.PreferredLanguage != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.did":
		x.Did = ""
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.active_gf_only":
		x.ActiveGfOnly = false
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.preferred_language":
		x.PreferredLanguage = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryGetTrustRegistryRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.did":
		value := x.Did
		return protoreflect.ValueOfString(value)
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.active_gf_only":
		value := x.ActiveGfOnly
		return protoreflect.ValueOfBool(value)
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.preferred_language":
		value := x.PreferredLanguage
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.did":
		x.Did = value.Interface().(string)
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.active_gf_only":
		x.ActiveGfOnly = value.Bool()
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.preferred_language":
		x.PreferredLanguage = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.did":
		panic(fmt.Errorf("field did of message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest is not mutable"))
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.active_gf_only":
		panic(fmt.Errorf("field active_gf_only of message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest is not mutable"))
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.preferred_language":
		panic(fmt.Errorf("field preferred_language of message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryGetTrustRegistryRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.did":
		return protoreflect.ValueOfString("")
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.active_gf_only":
		return protoreflect.ValueOfBool(false)
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest.preferred_language":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryGetTrustRegistryRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryGetTrustRegistryRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryGetTrustRegistryRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryGetTrustRegistryRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryGetTrustRegistryRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Did)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.ActiveGfOnly {
			n += 2
		}
		l = len(x.PreferredLanguage)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryGetTrustRegistryRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.PreferredLanguage) > 0 {
			i -= len(x.PreferredLanguage)
			copy(dAtA[i:], x.PreferredLanguage)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PreferredLanguage)))
			i--
			dAtA[i] = 0x1a
		}
		if x.ActiveGfOnly {
			i--
			if x.ActiveGfOnly {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x10
		}
		if len(x.Did) > 0 {
			i -= len(x.Did)
			copy(dAtA[i:], x.Did)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Did)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryGetTrustRegistryRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryGetTrustRegistryRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryGetTrustRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Did = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ActiveGfOnly", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.ActiveGfOnly = bool(v != 0)
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PreferredLanguage", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PreferredLanguage = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_QueryGetTrustRegistryResponse_2_list)(nil)

type _QueryGetTrustRegistryResponse_2_list struct {
	list *[]*GovernanceFrameworkVersion
}

func (x *_QueryGetTrustRegistryResponse_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_QueryGetTrustRegistryResponse_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_QueryGetTrustRegistryResponse_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*GovernanceFrameworkVersion)
	(*x.list)[i] = concreteValue
}

func (x *_QueryGetTrustRegistryResponse_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*GovernanceFrameworkVersion)
	*x.list = append(*x.list, concreteValue)
}

func (x *_QueryGetTrustRegistryResponse_2_list) AppendMutable() protoreflect.Value {
	v := new(GovernanceFrameworkVersion)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_QueryGetTrustRegistryResponse_2_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_QueryGetTrustRegistryResponse_2_list) NewElement() protoreflect.Value {
	v := new(GovernanceFrameworkVersion)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_QueryGetTrustRegistryResponse_2_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_QueryGetTrustRegistryResponse_3_list)(nil)

type _QueryGetTrustRegistryResponse_3_list struct {
	list *[]*GovernanceFrameworkDocument
}

func (x *_QueryGetTrustRegistryResponse_3_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_QueryGetTrustRegistryResponse_3_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_QueryGetTrustRegistryResponse_3_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*GovernanceFrameworkDocument)
	(*x.list)[i] = concreteValue
}

func (x *_QueryGetTrustRegistryResponse_3_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*GovernanceFrameworkDocument)
	*x.list = append(*x.list, concreteValue)
}

func (x *_QueryGetTrustRegistryResponse_3_list) AppendMutable() protoreflect.Value {
	v := new(GovernanceFrameworkDocument)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_QueryGetTrustRegistryResponse_3_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_QueryGetTrustRegistryResponse_3_list) NewElement() protoreflect.Value {
	v := new(GovernanceFrameworkDocument)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_QueryGetTrustRegistryResponse_3_list) IsValid() bool {
	return x.list != nil
}

var (
	md_QueryGetTrustRegistryResponse                protoreflect.MessageDescriptor
	fd_QueryGetTrustRegistryResponse_trust_registry protoreflect.FieldDescriptor
	fd_QueryGetTrustRegistryResponse_versions       protoreflect.FieldDescriptor
	fd_QueryGetTrustRegistryResponse_documents      protoreflect.FieldDescriptor
)

func init() {
	file_pratikasr_trustregistry_v1_query_proto_init()
	md_QueryGetTrustRegistryResponse = File_pratikasr_trustregistry_v1_query_proto.Messages().ByName("QueryGetTrustRegistryResponse")
	fd_QueryGetTrustRegistryResponse_trust_registry = md_QueryGetTrustRegistryResponse.Fields().ByName("trust_registry")
	fd_QueryGetTrustRegistryResponse_versions = md_QueryGetTrustRegistryResponse.Fields().ByName("versions")
	fd_QueryGetTrustRegistryResponse_documents = md_QueryGetTrustRegistryResponse.Fields().ByName("documents")
}

var _ protoreflect.Message = (*fastReflection_QueryGetTrustRegistryResponse)(nil)

type fastReflection_QueryGetTrustRegistryResponse QueryGetTrustRegistryResponse

func (x *QueryGetTrustRegistryResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryGetTrustRegistryResponse)(x)
}

func (x *QueryGetTrustRegistryResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_pratikasr_trustregistry_v1_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryGetTrustRegistryResponse_messageType fastReflection_QueryGetTrustRegistryResponse_messageType
var _ protoreflect.MessageType = fastReflection_QueryGetTrustRegistryResponse_messageType{}

type fastReflection_QueryGetTrustRegistryResponse_messageType struct{}

func (x fastReflection_QueryGetTrustRegistryResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryGetTrustRegistryResponse)(nil)
}
func (x fastReflection_QueryGetTrustRegistryResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryGetTrustRegistryResponse)
}
func (x fastReflection_QueryGetTrustRegistryResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryGetTrustRegistryResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryGetTrustRegistryResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryGetTrustRegistryResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryGetTrustRegistryResponse) Type() protoreflect.MessageType {
	return _fastReflection_QueryGetTrustRegistryResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryGetTrustRegistryResponse) New() protoreflect.Message {
	return new(fastReflection_QueryGetTrustRegistryResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryGetTrustRegistryResponse) Interface() protoreflect.ProtoMessage {
	return (*QueryGetTrustRegistryResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryGetTrustRegistryResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.TrustRegistry != nil {
		value := protoreflect.ValueOfMessage(x.TrustRegistry.ProtoReflect())
		if !f(fd_QueryGetTrustRegistryResponse_trust_registry, value) {
			return
		}
	}
	if len(x.Versions) != 0 {
		value := protoreflect.ValueOfList(&_QueryGetTrustRegistryResponse_2_list{list: &x.Versions})
		if !f(fd_QueryGetTrustRegistryResponse_versions, value) {
			return
		}
	}
	if len(x.Documents) != 0 {
		value := protoreflect.ValueOfList(&_QueryGetTrustRegistryResponse_3_list{list: &x.Documents})
		if !f(fd_QueryGetTrustRegistryResponse_documents, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryGetTrustRegistryResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.trust_registry":
		return x.TrustRegistry != nil
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.versions":
		return len(x.Versions) != 0
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.documents":
		return len(x.Documents) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.trust_registry":
		x.TrustRegistry = nil
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.versions":
		x.Versions = nil
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.documents":
		x.Documents = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryGetTrustRegistryResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.trust_registry":
		value := x.TrustRegistry
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.versions":
		if len(x.Versions) == 0 {
			return protoreflect.ValueOfList(&_QueryGetTrustRegistryResponse_2_list{})
		}
		listValue := &_QueryGetTrustRegistryResponse_2_list{list: &x.Versions}
		return protoreflect.ValueOfList(listValue)
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.documents":
		if len(x.Documents) == 0 {
			return protoreflect.ValueOfList(&_QueryGetTrustRegistryResponse_3_list{})
		}
		listValue := &_QueryGetTrustRegistryResponse_3_list{list: &x.Documents}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.trust_registry":
		x.TrustRegistry = value.Message().Interface().(*TrustRegistry)
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.versions":
		lv := value.List()
		clv := lv.(*_QueryGetTrustRegistryResponse_2_list)
		x.Versions = *clv.list
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.documents":
		lv := value.List()
		clv := lv.(*_QueryGetTrustRegistryResponse_3_list)
		x.Documents = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.trust_registry":
		if x.TrustRegistry == nil {
			x.TrustRegistry = new(TrustRegistry)
		}
		return protoreflect.ValueOfMessage(x.TrustRegistry.ProtoReflect())
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.versions":
		if x.Versions == nil {
			x.Versions = []*GovernanceFrameworkVersion{}
		}
		value := &_QueryGetTrustRegistryResponse_2_list{list: &x.Versions}
		return protoreflect.ValueOfList(value)
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.documents":
		if x.Documents == nil {
			x.Documents = []*GovernanceFrameworkDocument{}
		}
		value := &_QueryGetTrustRegistryResponse_3_list{list: &x.Documents}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryGetTrustRegistryResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.trust_registry":
		m := new(TrustRegistry)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.versions":
		list := []*GovernanceFrameworkVersion{}
		return protoreflect.ValueOfList(&_QueryGetTrustRegistryResponse_2_list{list: &list})
	case "pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.documents":
		list := []*GovernanceFrameworkDocument{}
		return protoreflect.ValueOfList(&_QueryGetTrustRegistryResponse_3_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryGetTrustRegistryResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryGetTrustRegistryResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryGetTrustRegistryResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryGetTrustRegistryResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryGetTrustRegistryResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryGetTrustRegistryResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.TrustRegistry != nil {
			l = options.Size(x.TrustRegistry)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.Versions) > 0 {
			for _, e := range x.Versions {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Documents) > 0 {
			for _, e := range x.Documents {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryGetTrustRegistryResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Documents) > 0 {
			for iNdEx := len(x.Documents) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Documents[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x1a
			}
		}
		if len(x.Versions) > 0 {
			for iNdEx := len(x.Versions) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Versions[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x12
			}
		}
		if x.TrustRegistry != nil {
			encoded, err := options.Marshal(x.TrustRegistry)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryGetTrustRegistryResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryGetTrustRegistryResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryGetTrustRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TrustRegistry", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.TrustRegistry == nil {
					x.TrustRegistry = &TrustRegistry{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.TrustRegistry); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Versions", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Versions = append(x.Versions, &GovernanceFrameworkVersion{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Versions[len(x.Versions)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Documents = append(x.Documents, &GovernanceFrameworkDocument{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Documents[len(x.Documents)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: pratikasr/trustregistry/v1/query.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryGetTrustRegistryRequest is the request type for the Query/GetTrustRegistry RPC method.
type QueryGetTrustRegistryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did               string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	ActiveGfOnly      bool   `protobuf:"varint,2,opt,name=active_gf_only,json=activeGfOnly,proto3" json:"active_gf_only,omitempty"`
	PreferredLanguage string `protobuf:"bytes,3,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
}

func (x *QueryGetTrustRegistryRequest) Reset() {
	*x = QueryGetTrustRegistryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pratikasr_trustregistry_v1_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGetTrustRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetTrustRegistryRequest) ProtoMessage() {}

// Deprecated: Use QueryGetTrustRegistryRequest.ProtoReflect.Descriptor instead.
func (*QueryGetTrustRegistryRequest) Descriptor() ([]byte, []int) {
	return file_pratikasr_trustregistry_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryGetTrustRegistryRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *QueryGetTrustRegistryRequest) GetActiveGfOnly() bool {
	if x != nil {
		return x.ActiveGfOnly
	}
	return false
}

func (x *QueryGetTrustRegistryRequest) GetPreferredLanguage() string {
	if x != nil {
		return x.PreferredLanguage
	}
	return ""
}

// QueryGetTrustRegistryResponse is the response type for the Query/GetTrustRegistry RPC method.
type QueryGetTrustRegistryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrustRegistry *TrustRegistry                 `protobuf:"bytes,1,opt,name=trust_registry,json=trustRegistry,proto3" json:"trust_registry,omitempty"`
	Versions      []*GovernanceFrameworkVersion  `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	Documents     []*GovernanceFrameworkDocument `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
}

func (x *QueryGetTrustRegistryResponse) Reset() {
	*x = QueryGetTrustRegistryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pratikasr_trustregistry_v1_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGetTrustRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetTrustRegistryResponse) ProtoMessage() {}

// Deprecated: Use QueryGetTrustRegistryResponse.ProtoReflect.Descriptor instead.
func (*QueryGetTrustRegistryResponse) Descriptor() ([]byte, []int) {
	return file_pratikasr_trustregistry_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryGetTrustRegistryResponse) GetTrustRegistry() *TrustRegistry {
	if x != nil {
		return x.TrustRegistry
	}
	return nil
}

func (x *QueryGetTrustRegistryResponse) GetVersions() []*GovernanceFrameworkVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *QueryGetTrustRegistryResponse) GetDocuments() []*GovernanceFrameworkDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_pratikasr_trustregistry_v1_query_proto protoreflect.FileDescriptor

var file_pratikasr_trustregistry_v1_query_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2f, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b,
	0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x26, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2f, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x1c, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x24, 0x0a,
	0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x67, 0x66, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x47, 0x66, 0x4f,
	0x6e, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64,
	0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x22, 0x9c, 0x02, 0x0a, 0x1d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70,
	0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x52, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x70, 0x72, 0x61, 0x74, 0x69,
	0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x55, 0x0a, 0x09, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e,
	0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x76, 0x65, 0x72,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0xc1, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0xb7, 0x01, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x12, 0x38, 0x2e, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75,
	0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x70, 0x72, 0x61,
	0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x65, 0x74,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x12, 0x26, 0x2f,
	0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f,
	0x7b, 0x64, 0x69, 0x64, 0x7d, 0x42, 0x89, 0x02, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72,
	0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2f, 0x74, 0x72, 0x75,
	0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50, 0x54, 0x58, 0xaa,
	0x02, 0x1a, 0x50, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2e, 0x54, 0x72, 0x75, 0x73,
	0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x1a, 0x50,
	0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x5c, 0x54, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x26, 0x50, 0x72, 0x61, 0x74,
	0x69, 0x6b, 0x61, 0x73, 0x72, 0x5c, 0x54, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x1c, 0x50, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x3a, 0x3a,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pratikasr_trustregistry_v1_query_proto_rawDescOnce sync.Once
	file_pratikasr_trustregistry_v1_query_proto_rawDescData = file_pratikasr_trustregistry_v1_query_proto_rawDesc
)

func file_pratikasr_trustregistry_v1_query_proto_rawDescGZIP() []byte {
	file_pratikasr_trustregistry_v1_query_proto_rawDescOnce.Do(func() {
		file_pratikasr_trustregistry_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_pratikasr_trustregistry_v1_query_proto_rawDescData)
	})
	return file_pratikasr_trustregistry_v1_query_proto_rawDescData
}

var file_pratikasr_trustregistry_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pratikasr_trustregistry_v1_query_proto_goTypes = []interface{}{
	(*QueryGetTrustRegistryRequest)(nil),  // 0: pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest
	(*QueryGetTrustRegistryResponse)(nil), // 1: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse
	(*TrustRegistry)(nil),                 // 2: pratikasr.trustregistry.v1.TrustRegistry
	(*GovernanceFrameworkVersion)(nil),    // 3: pratikasr.trustregistry.v1.GovernanceFrameworkVersion
	(*GovernanceFrameworkDocument)(nil),   // 4: pratikasr.trustregistry.v1.GovernanceFrameworkDocument
}
var file_pratikasr_trustregistry_v1_query_proto_depIdxs = []int32{
	2, // 0: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.trust_registry:type_name -> pratikasr.trustregistry.v1.TrustRegistry
	3, // 1: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.versions:type_name -> pratikasr.trustregistry.v1.GovernanceFrameworkVersion
	4, // 2: pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse.documents:type_name -> pratikasr.trustregistry.v1.GovernanceFrameworkDocument
	0, // 3: pratikasr.trustregistry.v1.Query.GetTrustRegistry:input_type -> pratikasr.trustregistry.v1.QueryGetTrustRegistryRequest
	1, // 4: pratikasr.trustregistry.v1.Query.GetTrustRegistry:output_type -> pratikasr.trustregistry.v1.QueryGetTrustRegistryResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pratikasr_trustregistry_v1_query_proto_init() }
func file_pratikasr_trustregistry_v1_query_proto_init() {
	if File_pratikasr_trustregistry_v1_query_proto != nil {
		return
	}
	file_pratikasr_trustregistry_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pratikasr_trustregistry_v1_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGetTrustRegistryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pratikasr_trustregistry_v1_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGetTrustRegistryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pratikasr_trustregistry_v1_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pratikasr_trustregistry_v1_query_proto_goTypes,
		DependencyIndexes: file_pratikasr_trustregistry_v1_query_proto_depIdxs,
		MessageInfos:      file_pratikasr_trustregistry_v1_query_proto_msgTypes,
	}.Build()
	File_pratikasr_trustregistry_v1_query_proto = out.File
	file_pratikasr_trustregistry_v1_query_proto_rawDesc = nil
	file_pratikasr_trustregistry_v1_query_proto_goTypes = nil
	file_pratikasr_trustregistry_v1_query_proto_depIdxs = nil
}
