// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package trustregistryv1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_MsgCreateTrustRegistry          protoreflect.MessageDescriptor
	fd_MsgCreateTrustRegistry_creator  protoreflect.FieldDescriptor
	fd_MsgCreateTrustRegistry_did      protoreflect.FieldDescriptor
	fd_MsgCreateTrustRegistry_aka      protoreflect.FieldDescriptor
	fd_MsgCreateTrustRegistry_language protoreflect.FieldDescriptor
	fd_MsgCreateTrustRegistry_doc_url  protoreflect.FieldDescriptor
	fd_MsgCreateTrustRegistry_doc_hash protoreflect.FieldDescriptor
)

func init() {
	file_pratikasr_trustregistry_v1_tx_proto_init()
	md_MsgCreateTrustRegistry = File_pratikasr_trustregistry_v1_tx_proto.Messages().ByName("MsgCreateTrustRegistry")
	fd_MsgCreateTrustRegistry_creator = md_MsgCreateTrustRegistry.Fields().ByName("creator")
	fd_MsgCreateTrustRegistry_did = md_MsgCreateTrustRegistry.Fields().ByName("did")
	fd_MsgCreateTrustRegistry_aka = md_MsgCreateTrustRegistry.Fields().ByName("aka")
	fd_MsgCreateTrustRegistry_language = md_MsgCreateTrustRegistry.Fields().ByName("language")
	fd_MsgCreateTrustRegistry_doc_url = md_MsgCreateTrustRegistry.Fields().ByName("doc_url")
	fd_MsgCreateTrustRegistry_doc_hash = md_MsgCreateTrustRegistry.Fields().ByName("doc_hash")
}

var _ protoreflect.Message = (*fastReflection_MsgCreateTrustRegistry)(nil)

type fastReflection_MsgCreateTrustRegistry MsgCreateTrustRegistry

func (x *MsgCreateTrustRegistry) ProtoReflect() protoreflect.Message {
	return (*fastReflection_MsgCreateTrustRegistry)(x)
}

func (x *MsgCreateTrustRegistry) slowProtoReflect() protoreflect.Message {
	mi := &file_pratikasr_trustregistry_v1_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_MsgCreateTrustRegistry_messageType fastReflection_MsgCreateTrustRegistry_messageType
var _ protoreflect.MessageType = fastReflection_MsgCreateTrustRegistry_messageType{}

type fastReflection_MsgCreateTrustRegistry_messageType struct{}

func (x fastReflection_MsgCreateTrustRegistry_messageType) Zero() protoreflect.Message {
	return (*fastReflection_MsgCreateTrustRegistry)(nil)
}
func (x fastReflection_MsgCreateTrustRegistry_messageType) New() protoreflect.Message {
	return new(fastReflection_MsgCreateTrustRegistry)
}
func (x fastReflection_MsgCreateTrustRegistry_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgCreateTrustRegistry
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_MsgCreateTrustRegistry) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgCreateTrustRegistry
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_MsgCreateTrustRegistry) Type() protoreflect.MessageType {
	return _fastReflection_MsgCreateTrustRegistry_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_MsgCreateTrustRegistry) New() protoreflect.Message {
	return new(fastReflection_MsgCreateTrustRegistry)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_MsgCreateTrustRegistry) Interface() protoreflect.ProtoMessage {
	return (*MsgCreateTrustRegistry)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_MsgCreateTrustRegistry) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_MsgCreateTrustRegistry_creator, value) {
			return
		}
	}
	if x.Did != "" {
		value := protoreflect.ValueOfString(x.Did)
		if !f(fd_MsgCreateTrustRegistry_did, value) {
			return
		}
	}
	if x.Aka != "" {
		value := protoreflect.ValueOfString(x.Aka)
		if !f(fd_MsgCreateTrustRegistry_aka, value) {
			return
		}
	}
	if x.Language != "" {
		value := protoreflect.ValueOfString(x.Language)
		if !f(fd_MsgCreateTrustRegistry_language, value) {
			return
		}
	}
	if x.DocUrl != "" {
		value := protoreflect.ValueOfString(x.DocUrl)
		if !f(fd_MsgCreateTrustRegistry_doc_url, value) {
			return
		}
	}
	if x.DocHash != "" {
		value := protoreflect.ValueOfString(x.DocHash)
		if !f(fd_MsgCreateTrustRegistry_doc_hash, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_MsgCreateTrustRegistry) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.creator":
		return x.Creator != ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.did":
		return x.Did != ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.aka":
		return x.Aka != ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.language":
		return x.Language != ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_url":
		return x.DocUrl != ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_hash":
		return x.DocHash != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistry"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistry does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistry) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.creator":
		x.Creator = ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.did":
		x.Did = ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.aka":
		x.Aka = ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.language":
		x.Language = ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_url":
		x.DocUrl = ""
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_hash":
		x.DocHash = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistry"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistry does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_MsgCreateTrustRegistry) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.did":
		value := x.Did
		return protoreflect.ValueOfString(value)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.aka":
		value := x.Aka
		return protoreflect.ValueOfString(value)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.language":
		value := x.Language
		return protoreflect.ValueOfString(value)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_url":
		value := x.DocUrl
		return protoreflect.ValueOfString(value)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_hash":
		value := x.DocHash
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistry"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistry does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistry) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.creator":
		x.Creator = value.Interface().(string)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.did":
		x.Did = value.Interface().(string)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.aka":
		x.Aka = value.Interface().(string)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.language":
		x.Language = value.Interface().(string)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_url":
		x.DocUrl = value.Interface().(string)
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_hash":
		x.DocHash = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistry"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistry does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistry) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.creator":
		panic(fmt.Errorf("field creator of message pratikasr.trustregistry.v1.MsgCreateTrustRegistry is not mutable"))
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.did":
		panic(fmt.Errorf("field did of message pratikasr.trustregistry.v1.MsgCreateTrustRegistry is not mutable"))
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.aka":
		panic(fmt.Errorf("field aka of message pratikasr.trustregistry.v1.MsgCreateTrustRegistry is not mutable"))
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.language":
		panic(fmt.Errorf("field language of message pratikasr.trustregistry.v1.MsgCreateTrustRegistry is not mutable"))
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_url":
		panic(fmt.Errorf("field doc_url of message pratikasr.trustregistry.v1.MsgCreateTrustRegistry is not mutable"))
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_hash":
		panic(fmt.Errorf("field doc_hash of message pratikasr.trustregistry.v1.MsgCreateTrustRegistry is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistry"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistry does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_MsgCreateTrustRegistry) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.creator":
		return protoreflect.ValueOfString("")
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.did":
		return protoreflect.ValueOfString("")
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.aka":
		return protoreflect.ValueOfString("")
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.language":
		return protoreflect.ValueOfString("")
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_url":
		return protoreflect.ValueOfString("")
	case "pratikasr.trustregistry.v1.MsgCreateTrustRegistry.doc_hash":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistry"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistry does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_MsgCreateTrustRegistry) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in pratikasr.trustregistry.v1.MsgCreateTrustRegistry", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_MsgCreateTrustRegistry) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistry) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_MsgCreateTrustRegistry) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_MsgCreateTrustRegistry) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*MsgCreateTrustRegistry)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Did)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Aka)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Language)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DocUrl)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DocHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*MsgCreateTrustRegistry)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.DocHash) > 0 {
			i -= len(x.DocHash)
			copy(dAtA[i:], x.DocHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DocHash)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.DocUrl) > 0 {
			i -= len(x.DocUrl)
			copy(dAtA[i:], x.DocUrl)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DocUrl)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Language) > 0 {
			i -= len(x.Language)
			copy(dAtA[i:], x.Language)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Language)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Aka) > 0 {
			i -= len(x.Aka)
			copy(dAtA[i:], x.Aka)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Aka)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Did) > 0 {
			i -= len(x.Did)
			copy(dAtA[i:], x.Did)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Did)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*MsgCreateTrustRegistry)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgCreateTrustRegistry: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgCreateTrustRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Did = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Aka", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Aka = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Language = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DocUrl", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DocUrl = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DocHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DocHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_MsgCreateTrustRegistryResponse protoreflect.MessageDescriptor
)

func init() {
	file_pratikasr_trustregistry_v1_tx_proto_init()
	md_MsgCreateTrustRegistryResponse = File_pratikasr_trustregistry_v1_tx_proto.Messages().ByName("MsgCreateTrustRegistryResponse")
}

var _ protoreflect.Message = (*fastReflection_MsgCreateTrustRegistryResponse)(nil)

type fastReflection_MsgCreateTrustRegistryResponse MsgCreateTrustRegistryResponse

func (x *MsgCreateTrustRegistryResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_MsgCreateTrustRegistryResponse)(x)
}

func (x *MsgCreateTrustRegistryResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_pratikasr_trustregistry_v1_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_MsgCreateTrustRegistryResponse_messageType fastReflection_MsgCreateTrustRegistryResponse_messageType
var _ protoreflect.MessageType = fastReflection_MsgCreateTrustRegistryResponse_messageType{}

type fastReflection_MsgCreateTrustRegistryResponse_messageType struct{}

func (x fastReflection_MsgCreateTrustRegistryResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_MsgCreateTrustRegistryResponse)(nil)
}
func (x fastReflection_MsgCreateTrustRegistryResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_MsgCreateTrustRegistryResponse)
}
func (x fastReflection_MsgCreateTrustRegistryResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgCreateTrustRegistryResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgCreateTrustRegistryResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Type() protoreflect.MessageType {
	return _fastReflection_MsgCreateTrustRegistryResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_MsgCreateTrustRegistryResponse) New() protoreflect.Message {
	return new(fastReflection_MsgCreateTrustRegistryResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Interface() protoreflect.ProtoMessage {
	return (*MsgCreateTrustRegistryResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistryResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_MsgCreateTrustRegistryResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse"))
		}
		panic(fmt.Errorf("message pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_MsgCreateTrustRegistryResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_MsgCreateTrustRegistryResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgCreateTrustRegistryResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_MsgCreateTrustRegistryResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_MsgCreateTrustRegistryResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*MsgCreateTrustRegistryResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*MsgCreateTrustRegistryResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*MsgCreateTrustRegistryResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgCreateTrustRegistryResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgCreateTrustRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: pratikasr/trustregistry/v1/tx.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateTrustRegistry defines the Msg/CreateTrustRegistry request type.
type MsgCreateTrustRegistry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Did      string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	Aka      string `protobuf:"bytes,3,opt,name=aka,proto3" json:"aka,omitempty"`
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	DocUrl   string `protobuf:"bytes,5,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	DocHash  string `protobuf:"bytes,6,opt,name=doc_hash,json=docHash,proto3" json:"doc_hash,omitempty"`
}

func (x *MsgCreateTrustRegistry) Reset() {
	*x = MsgCreateTrustRegistry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pratikasr_trustregistry_v1_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateTrustRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateTrustRegistry) ProtoMessage() {}

// Deprecated: Use MsgCreateTrustRegistry.ProtoReflect.Descriptor instead.
func (*MsgCreateTrustRegistry) Descriptor() ([]byte, []int) {
	return file_pratikasr_trustregistry_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateTrustRegistry) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateTrustRegistry) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *MsgCreateTrustRegistry) GetAka() string {
	if x != nil {
		return x.Aka
	}
	return ""
}

func (x *MsgCreateTrustRegistry) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *MsgCreateTrustRegistry) GetDocUrl() string {
	if x != nil {
		return x.DocUrl
	}
	return ""
}

func (x *MsgCreateTrustRegistry) GetDocHash() string {
	if x != nil {
		return x.DocHash
	}
	return ""
}

// MsgCreateTrustRegistryResponse defines the Msg/CreateTrustRegistry response type.
type MsgCreateTrustRegistryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgCreateTrustRegistryResponse) Reset() {
	*x = MsgCreateTrustRegistryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pratikasr_trustregistry_v1_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateTrustRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateTrustRegistryResponse) ProtoMessage() {}

// Deprecated: Use MsgCreateTrustRegistryResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateTrustRegistryResponse) Descriptor() ([]byte, []int) {
	return file_pratikasr_trustregistry_v1_tx_proto_rawDescGZIP(), []int{1}
}

var File_pratikasr_trustregistry_v1_tx_proto protoreflect.FileDescriptor

var file_pratikasr_trustregistry_v1_tx_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2f, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x78, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72,
	0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76,
	0x31, 0x1a, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x01, 0x0a, 0x16, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x12, 0x32, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6b, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6b, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x6f, 0x63, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a,
	0x08, 0x64, 0x6f, 0x63, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x6f, 0x63, 0x48, 0x61, 0x73, 0x68, 0x3a, 0x0c, 0x82, 0xe7, 0xb0, 0x2a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x20, 0x0a, 0x1e, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x94, 0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x12, 0x85, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x32, 0x2e, 0x70, 0x72, 0x61, 0x74, 0x69,
	0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x1a, 0x3a, 0x2e, 0x70,
	0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x05, 0x80, 0xe7, 0xb0, 0x2a, 0x01, 0x42,
	0x86, 0x02, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73,
	0x72, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e,
	0x76, 0x31, 0x42, 0x07, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x51, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b,
	0x61, 0x73, 0x72, 0x2f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x2f,
	0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31,
	0x3b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x50, 0x54, 0x58, 0xaa, 0x02, 0x1a, 0x50, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61,
	0x73, 0x72, 0x2e, 0x54, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x1a, 0x50, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x5c,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x26, 0x50, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x61, 0x73, 0x72, 0x5c, 0x54, 0x72, 0x75,
	0x73, 0x74, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x1c, 0x50, 0x72, 0x61, 0x74,
	0x69, 0x6b, 0x61, 0x73, 0x72, 0x3a, 0x3a, 0x54, 0x72, 0x75, 0x73, 0x74, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pratikasr_trustregistry_v1_tx_proto_rawDescOnce sync.Once
	file_pratikasr_trustregistry_v1_tx_proto_rawDescData = file_pratikasr_trustregistry_v1_tx_proto_rawDesc
)

func file_pratikasr_trustregistry_v1_tx_proto_rawDescGZIP() []byte {
	file_pratikasr_trustregistry_v1_tx_proto_rawDescOnce.Do(func() {
		file_pratikasr_trustregistry_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_pratikasr_trustregistry_v1_tx_proto_rawDescData)
	})
	return file_pratikasr_trustregistry_v1_tx_proto_rawDescData
}

var file_pratikasr_trustregistry_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pratikasr_trustregistry_v1_tx_proto_goTypes = []interface{}{
	(*MsgCreateTrustRegistry)(nil),         // 0: pratikasr.trustregistry.v1.MsgCreateTrustRegistry
	(*MsgCreateTrustRegistryResponse)(nil), // 1: pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse
}
var file_pratikasr_trustregistry_v1_tx_proto_depIdxs = []int32{
	0, // 0: pratikasr.trustregistry.v1.Msg.CreateTrustRegistry:input_type -> pratikasr.trustregistry.v1.MsgCreateTrustRegistry
	1, // 1: pratikasr.trustregistry.v1.Msg.CreateTrustRegistry:output_type -> pratikasr.trustregistry.v1.MsgCreateTrustRegistryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pratikasr_trustregistry_v1_tx_proto_init() }
func file_pratikasr_trustregistry_v1_tx_proto_init() {
	if File_pratikasr_trustregistry_v1_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pratikasr_trustregistry_v1_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateTrustRegistry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pratikasr_trustregistry_v1_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateTrustRegistryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pratikasr_trustregistry_v1_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pratikasr_trustregistry_v1_tx_proto_goTypes,
		DependencyIndexes: file_pratikasr_trustregistry_v1_tx_proto_depIdxs,
		MessageInfos:      file_pratikasr_trustregistry_v1_tx_proto_msgTypes,
	}.Build()
	File_pratikasr_trustregistry_v1_tx_proto = out.File
	file_pratikasr_trustregistry_v1_tx_proto_rawDesc = nil
	file_pratikasr_trustregistry_v1_tx_proto_goTypes = nil
	file_pratikasr_trustregistry_v1_tx_proto_depIdxs = nil
}
